const mongoose = require("mongoose");

const zoneSchema = new mongoose.Schema(
  {
    // Gate Name
    name: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },

    // Crowd Level: 0–100
    crowdLevel: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },

    // Estimated waiting time in minutes
    waitTime: {
      type: Number,
      default: 0,
      min: 0,
    },

    // Gate Location
    lat: {
      type: Number,
      required: true,
    },

    lng: {
      type: Number,
      required: true,
    },

    // AI prediction
    prediction: {
      type: String,
      default: "Analyzing...",
    },

    // Crowd status
    status: {
      type: String,
      enum: ["Smooth", "Moderate", "High"],
      default: "Smooth",
    },

    // AI Risk Score: 0–100
    riskScore: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },

    // Risk classification
    riskLevel: {
      type: String,
      enum: ["Low", "Medium", "High"],
      default: "Low",
    },

    // Optional reason generated by AI
    riskReason: {
      type: String,
      default: "",
    },
  },
  {
    timestamps: true,
  }
);


// Automatically calculate crowd status
zoneSchema.pre("save", function (next) {
  if (this.crowdLevel > 70) {
    this.status = "High";
  } else if (this.crowdLevel > 40) {
    this.status = "Moderate";
  } else {
    this.status = "Smooth";
  }

  // Automatically calculate risk level
  if (this.riskScore > 70) {
    this.riskLevel = "High";
  } else if (this.riskScore > 40) {
    this.riskLevel = "Medium";
  } else {
    this.riskLevel = "Low";
  }

  next();
});


module.exports = mongoose.model("Zone", zoneSchema);